spring.datasource.url=jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=${BACKEND_PORT:8080}

# JWT
jwt.secret=304f42d8711889585a433a9ec28ebae231a3c379c61b6199023b6ae00a6d4a3d
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer
